# Site settings

project:
    name: "MagTool2"
    alt_name: "MagTool"
    tagline: Net-A-Porter Magazine Tool
    author: "NAPWebProductionEditTeam"
    github: "https://github.com/NAPWebProductionEditTeam/MagTool2"
    package: "NAPWebProductionEditTeam/MagTool2"
navigation:
  - name: Documentation
    url : "docs"
    navigation:
      - name: User
        url: "user"
        navigation:
          - name: Getting Started
            type: category
          - name: Installation
            type: page
            url: "installation"
          - name: Start Editing
            type: page
            url: "start-edit"
          - name: Basic Editing Controls
            type: category
          - name: Selecting and Moving Elements
            type: page
            url: "general-editing"
          - name: Slug Controls
            type: page
            url: "slug-controls"
          - name: Credit Controls
            type: page
            url: "credits"
          - name: Advanced Tools
            type: category
          - name: Text Boxes
            type: page
            url: "text-boxes"
      - name: Developer
        url: "dev"
        navigation:
          - name: Getting Started
            type: category
          - name: Installation
            type: page
            url: "installation"
          - name: Local Builds
            type: page
            url: "local"
          - name: Application Structure
            type: page
            url: "structure"
          - name: The Basics
            type: category
          - name: Lifecycle
            type: page
            url: "lifecycle"
          - name: The Application
            type: page
            url: "application"
          - name: Actions
            type: page
            url: "actions"
          - name: Modules
            type: page
            url: "modules"
          - name: Release Process
            type: page
            url: "release"
          - name: API Reference
            type: category
          - name: API
            type: hide
            url: "api"
          - name: Anchor
            type: page
            url: "api/anchor"
          - name: Application
            type: page
            url: "api/application"
url: "https://napwebproductioneditteam.github.com/MagTool2"
github_username: NAPWebProductionEditTeam

# Build settings
exclude: ['build.sh']
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'with_toc_data', 'html_toc', 'strikethrough', 'autolink', 'tables', 'footnotes', 'underline']
highlighter: pygments
pygments_options: ['startinline']
gems: [jekyll-assets, nokogiri, octopress-minify-html, redcarpet, pygments.rb]
assets:
  compress:
    css: true
    js: true
  prefix: "assets"
  assets:
    - "app.css"
    - "app.js"
  digest: false
  sources:
    - _assets
